# Generated by Django 6.1.1 on 2026-09-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="hobbies",
        ),
    ]
