# Generated by Django 6.1.1 on 2026-10-01 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_title", models.CharField(max_length=150)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("duration", models.CharField(max_length=50)),
                ("course_image", models.ImageField(upload_to="courses/")),
                ("enrollment_start_date", models.DateTimeField()),
                ("enrollment_end_date", models.DateTimeField()),
                ("course_start_date", models.DateTimeField()),
                ("course_end_date", models.DateTimeField()),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
