# Generated by Django 6.1.1 on 2026-10-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "permissions": (
                    ("can_create_courses", "Provide grant to create courses."),
                    ("can_edit_courses", "Provide grant to Edit courses."),
                    ("can_delete_courses", "Provide grant to delete courses."),
                )
            },
        ),
    ]
